name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:
  schedule:
    - cron: '0 2 * * *'

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Build TypeScript and bundle
        run: npm run build
        
      - name: Install ImageMagick
        run: sudo apt-get update && sudo apt-get install -y imagemagick
        
      - name: Download and convert avatar to favicon with rounded corners
        run: |
          # Download GitHub avatar
          curl -L https://avatars.githubusercontent.com/u/126825095?v=4 -o avatar.png

          # Function to round corners of a PNG
          roundcorners() {
            local size=$1
            local radius=$(($size / 4))

            # Resize to fill the box and crop excess from the edges (preserve center)
            convert avatar.png -resize ${size}x${size}^ -gravity center -extent ${size}x${size} avatar_resized.png

            # Create a mask with a white rounded rectangle on black background
            convert -size ${size}x${size} xc:black -fill white \
              -draw "roundrectangle 0,0,$((size-1)),$((size-1)),$radius,$radius" \
              -blur 0x1 mask.png

            # Apply the mask to the resized avatar by copying the mask into the alpha channel
            convert avatar_resized.png mask.png -alpha set -compose CopyOpacity -composite favicon-${size}.png

            # Cleanup temporaries
            rm -f avatar_resized.png mask.png
          }

          # Create favicons with rounded corners in multiple sizes
          for size in 16 32 48 64; do
            roundcorners $size
          done

          # Create ICO file with multiple resolutions
          convert favicon-16.png favicon-32.png favicon-48.png favicon-64.png favicon.ico

          # Create a PNG favicon for modern browsers (rounded, 192x192)
          roundcorners 192
          mv favicon-192.png favicon.png

          # Copy favicons to the dist directory
          cp favicon.ico dist/
          cp favicon.png dist/
          
          # Clean up temporary files
          rm favicon-16.png favicon-32.png favicon-48.png favicon-64.png avatar.png
        
      - name: Setup Pages
        uses: actions/configure-pages@v4
        
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './dist'
          
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
